In [1]:
import cv2
import csv
import opencv_jupyter_ui as jcv2
import os
import pandas as pd
from feat import Detector
from IPython.display import Image

from feat.utils import FEAT_EMOTION_COLUMNS

In [2]:
import logging
logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)

In [56]:
detector = Detector(device="cuda", batch_size=20)

C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\face_detectors\Retinaface\Retinaface_test.py:70: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  pretrained_dict = torch.load(
C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:224: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(
C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\facepose_detectors\img2pose\img2pose_test.py:105: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(model_path, map_location=self.device)
C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\emo_detectors\ResMaskNet\resmasknet_test.py:718: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(

In [60]:
df = pd.DataFrame()
for emotion in os.listdir("./train"):
    print(emotion)
    test_images = ["./train/" + emotion + "/" + file for file in os.listdir("./train/" + emotion)]
    test_images = test_images[0:200]
    prediction = detector.detect_image(test_images, batch_size=20)
    prediction.insert(0, "emotion", emotion)
    df = pd.concat([df, prediction])

angry

  0%|                                                                          | 0/10 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 1/10 [00:19<02:55, 19.47s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 2/10 [00:40<02:44, 20.60s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 3/10 [01:00<02:22, 20.34s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 4/10 [01:22<02:05, 20.94s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████                                 | 5/10 [01:44<01:46, 21.39s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████▌                          | 6/10 [02:07<01:26, 21.75s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|██████████████████████████████████████████████▏                   | 7/10 [02:27<01:03, 21.33s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████▊             | 8/10 [02:50<00:43, 21.71s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|███████████████████████████████████████████████████████████▍      | 9/10 [03:12<00:21, 21.71s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 10/10 [03:33<00:00, 21.38s/it]

disgust

  0%|                                                                          | 0/10 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 1/10 [00:22<03:26, 22.93s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 2/10 [00:45<02:59, 22.49s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 3/10 [01:06<02:34, 22.10s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 4/10 [01:26<02:07, 21.23s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████                                 | 5/10 [01:47<01:46, 21.20s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████▌                          | 6/10 [02:09<01:25, 21.30s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|██████████████████████████████████████████████▏                   | 7/10 [02:29<01:02, 20.83s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████▊             | 8/10 [02:50<00:42, 21.07s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|███████████████████████████████████████████████████████████▍      | 9/10 [03:13<00:21, 21.49s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 10/10 [03:35<00:00, 21.55s/it]

fear

  0%|                                                                          | 0/10 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 1/10 [00:20<03:03, 20.39s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 2/10 [00:40<02:39, 19.96s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 3/10 [00:58<02:14, 19.22s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 4/10 [01:19<02:00, 20.10s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████                                 | 5/10 [01:46<01:53, 22.64s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████▌                          | 6/10 [02:11<01:33, 23.31s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|██████████████████████████████████████████████▏                   | 7/10 [02:33<01:08, 22.70s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████▊             | 8/10 [02:52<00:43, 21.58s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|███████████████████████████████████████████████████████████▍      | 9/10 [03:12<00:21, 21.25s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 10/10 [03:31<00:00, 21.13s/it]

happy

  0%|                                                                          | 0/10 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 1/10 [00:19<02:57, 19.71s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 2/10 [00:39<02:38, 19.78s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 3/10 [00:56<02:09, 18.50s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 4/10 [01:18<01:58, 19.80s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████                                 | 5/10 [01:39<01:41, 20.39s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████▌                          | 6/10 [01:58<01:19, 19.91s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|██████████████████████████████████████████████▏                   | 7/10 [02:18<00:59, 19.97s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████▊             | 8/10 [02:37<00:39, 19.54s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|███████████████████████████████████████████████████████████▍      | 9/10 [02:55<00:19, 19.13s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 10/10 [03:15<00:00, 19.51s/it]

neutral

  0%|                                                                          | 0/10 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 1/10 [00:20<03:00, 20.11s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 2/10 [00:38<02:34, 19.35s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 3/10 [00:58<02:14, 19.25s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 4/10 [01:18<01:58, 19.68s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████                                 | 5/10 [01:37<01:37, 19.59s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████▌                          | 6/10 [02:00<01:22, 20.50s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|██████████████████████████████████████████████▏                   | 7/10 [02:21<01:02, 20.82s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████▊             | 8/10 [02:40<00:40, 20.12s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|███████████████████████████████████████████████████████████▍      | 9/10 [03:00<00:20, 20.19s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 10/10 [03:20<00:00, 20.04s/it]

sad

  0%|                                                                          | 0/10 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 1/10 [00:17<02:41, 17.98s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 2/10 [00:36<02:26, 18.33s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 3/10 [00:55<02:11, 18.79s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 4/10 [01:16<01:56, 19.45s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████                                 | 5/10 [01:35<01:36, 19.33s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████▌                          | 6/10 [01:53<01:15, 18.93s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|██████████████████████████████████████████████▏                   | 7/10 [02:14<00:58, 19.48s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████▊             | 8/10 [02:35<00:39, 20.00s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|███████████████████████████████████████████████████████████▍      | 9/10 [02:54<00:19, 19.76s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 10/10 [03:13<00:00, 19.30s/it]

surprise

  0%|                                                                          | 0/10 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 1/10 [00:20<03:05, 20.63s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 2/10 [00:40<02:40, 20.05s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 3/10 [01:00<02:21, 20.15s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 4/10 [01:18<01:55, 19.30s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████                                 | 5/10 [01:38<01:36, 19.36s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████▌                          | 6/10 [01:58<01:19, 19.89s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|██████████████████████████████████████████████▏                   | 7/10 [02:20<01:00, 20.30s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████▊             | 8/10 [02:44<00:43, 21.55s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|███████████████████████████████████████████████████████████▍      | 9/10 [03:03<00:20, 20.74s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 10/10 [03:25<00:00, 20.57s/it]

In [61]:
df

,emotion,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,input,frame
0,angry,-0.317144,-0.296612,36.386595,47.857693,0.993587,1.813974,1.133883,1.385370,2.702636,...,0.047674,0.774246,0.001278,0.011921,0.000004,0.206298,0.000265,0.005990,./train/angry/0.jpg,0
1,angry,4.582017,6.066693,36.213592,42.817191,0.936886,5.151398,5.856383,7.202157,9.030707,...,0.331281,0.018104,0.000060,0.083588,0.005379,0.027696,0.828093,0.037080,./train/angry/1.jpg,1
2,angry,3.020084,-1.337374,42.367115,50.018351,0.955637,4.206306,4.381433,5.386287,7.068583,...,0.312888,0.998978,0.000704,0.000179,0.000026,0.000036,0.000067,0.000010,./train/angry/10.jpg,2
3,angry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,./train/angry/1015.jpg,3
4,angry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,./train/angry/1016.jpg,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,surprise,6.517096,5.912450,36.471354,40.120967,0.993008,6.983612,6.769625,6.826201,7.364524,...,0.110185,0.010074,0.000192,0.036296,0.025369,0.000208,0.926179,0.001683,./train/surprise/12201.jpg,195
196,surprise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,./train/surprise/12219.jpg,196
197,surprise,3.710874,0.839149,38.777411,48.596615,0.988135,2.740710,3.007276,4.110514,6.042857,...,0.089686,0.001476,0.000135,0.000202,0.002379,0.004351,0.900471,0.090985,./train/surprise/12224.jpg,197
198,surprise,6.617387,-0.726949,42.000811,51.136228,0.984618,10.280347,10.011926,10.735785,12.542894,...,0.278808,0.002271,0.000030,0.000569,0.625110,0.000040,0.371645,0.000335,./train/surprise/12226.jpg,198
199,surprise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,./train/surprise/1224.jpg,199

In [62]:
original = df.copy()
df=df.dropna(axis=0)
df

,emotion,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,input,frame
0,angry,-0.317144,-0.296612,36.386595,47.857693,0.993587,1.813974,1.133883,1.385370,2.702636,...,0.047674,0.774246,0.001278,0.011921,0.000004,0.206298,0.000265,0.005990,./train/angry/0.jpg,0
1,angry,4.582017,6.066693,36.213592,42.817191,0.936886,5.151398,5.856383,7.202157,9.030707,...,0.331281,0.018104,0.000060,0.083588,0.005379,0.027696,0.828093,0.037080,./train/angry/1.jpg,1
2,angry,3.020084,-1.337374,42.367115,50.018351,0.955637,4.206306,4.381433,5.386287,7.068583,...,0.312888,0.998978,0.000704,0.000179,0.000026,0.000036,0.000067,0.000010,./train/angry/10.jpg,2
5,angry,4.326479,-0.104184,39.572317,46.208394,0.995419,4.997071,6.131124,7.816174,9.829297,...,0.278808,0.988177,0.000465,0.000062,0.000135,0.006311,0.000107,0.004742,./train/angry/1018.jpg,5
6,angry,6.746211,3.805352,35.161420,42.337760,0.988647,8.762886,10.136482,11.949142,14.173568,...,0.278808,0.999215,0.000006,0.000004,0.000003,0.000114,0.000002,0.000657,./train/angry/1039.jpg,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,surprise,4.530496,2.145038,36.796950,44.385377,0.560110,7.816280,8.054595,9.124520,10.736418,...,0.063649,0.121353,0.000068,0.412031,0.000791,0.014559,0.447389,0.003809,./train/surprise/12176.jpg,192
194,surprise,2.838645,-0.808682,42.107735,51.421369,0.947221,1.700117,1.955173,3.103395,5.025530,...,0.200515,0.002278,0.000060,0.187326,0.000115,0.000068,0.809619,0.000534,./train/surprise/12195.jpg,194
195,surprise,6.517096,5.912450,36.471354,40.120967,0.993008,6.983612,6.769625,6.826201,7.364524,...,0.110185,0.010074,0.000192,0.036296,0.025369,0.000208,0.926179,0.001683,./train/surprise/12201.jpg,195
197,surprise,3.710874,0.839149,38.777411,48.596615,0.988135,2.740710,3.007276,4.110514,6.042857,...,0.089686,0.001476,0.000135,0.000202,0.002379,0.004351,0.900471,0.090985,./train/surprise/12224.jpg,197
198,surprise,6.617387,-0.726949,42.000811,51.136228,0.984618,10.280347,10.011926,10.735785,12.542894,...,0.278808,0.002271,0.000030,0.000569,0.625110,0.000040,0.371645,0.000335,./train/surprise/12226.jpg,198

In [63]:
cpy = df.copy()
AUcol = [col for col in cpy if col.startswith('AU')]
cpy = cpy[["emotion"] + AUcol]
data = pd.read_csv(filepath_or_buffer = "dataset.csv")
data = pd.concat([data, cpy])
data.to_csv('aus000200.csv', index=False)  
data

,emotion,AU01,AU02,AU04,AU05,AU06,AU07,AU09,AU10,AU11,...,AU14,AU15,AU17,AU20,AU23,AU24,AU25,AU26,AU28,AU43
0,neutral,0.450774,0.289915,0.409713,0.518726,0.086218,0.0,0.187309,0.354838,0.0,...,0.320690,0.411641,0.431646,0.0,0.277122,0.335435,0.262999,0.189863,0.051967,0.051370
1,disgust,0.500450,0.314694,0.625174,0.335747,0.262984,0.0,0.504238,0.383201,0.0,...,0.544159,0.440429,0.495913,0.0,0.514737,0.420401,0.052358,0.143576,0.500994,0.155117
2,sad,0.273191,0.191327,0.140938,0.358091,0.246593,0.0,0.312881,0.188845,1.0,...,0.284598,0.761539,0.491468,0.0,0.134049,0.670237,0.024796,0.109462,0.325429,0.191367
3,neutral,0.464508,0.301702,0.500370,0.296161,0.189114,0.0,0.521304,0.039475,0.0,...,0.491734,0.163430,0.552469,0.0,0.419418,0.306920,0.224105,0.072518,0.652248,0.505568
4,happy,0.274483,0.232007,0.601821,0.281365,0.900241,1.0,0.784789,0.198816,0.0,...,0.703261,0.549239,0.425561,0.0,0.203916,0.561599,0.966706,0.108249,0.464104,0.786888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,surprise,0.524267,0.479465,0.149378,0.615785,0.082453,0.0,0.126618,0.000328,0.0,...,0.496496,0.219003,0.331698,0.0,0.594759,0.631617,0.003588,0.112354,0.214668,0.063649
194,surprise,0.597499,0.482100,0.491076,0.480302,0.098770,0.0,0.218045,0.022854,1.0,...,0.336812,0.484415,0.395170,1.0,0.612837,0.234319,0.943491,0.670824,0.333626,0.200515
195,surprise,0.498616,0.334121,0.458838,0.716371,0.058513,0.0,0.115252,0.078145,0.0,...,0.127927,0.241809,0.271890,0.0,0.602475,0.126110,0.514951,0.221690,0.377973,0.110185
197,surprise,0.821910,0.703785,0.190844,0.469023,0.808521,1.0,0.173420,0.230387,1.0,...,0.257196,0.170330,0.292547,1.0,0.088049,0.095901,0.990243,0.237863,0.031830,0.089686
198,surprise,0.611220,0.720979,0.183749,0.492074,0.149797,0.0,0.268492,0.276410,0.0,...,0.443315,0.757518,0.483660,1.0,0.554601,0.610148,0.140141,0.253162,0.246370,0.278808