In [1]:
import cv2
import csv
import os
import pandas as pd
from feat import Detector
from IPython.display import Image

from feat.utils import FEAT_EMOTION_COLUMNS

In [ ]:
import logging
logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)

In [3]:
detector = Detector(device="cuda", batch_size=20)

C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\face_detectors\Retinaface\Retinaface_test.py:70: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  pretrained_dict = torch.load(
C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:224: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(
C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\facepose_detectors\img2pose\img2pose_test.py:105: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(model_path, map_location=self.device)
C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\emo_detectors\ResMaskNet\resmasknet_test.py:718: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(

In [4]:
df = pd.DataFrame()
for emotion in os.listdir("./train"):
    print(emotion)
    test_images = ["./train/" + emotion + "/" + file for file in os.listdir("./train/" + emotion)]
    test_images = test_images[400:800]
    prediction = detector.detect_image(test_images, batch_size=20)
    prediction.insert(0, "emotion", emotion)
    df = pd.concat([df, prediction])

angry

  0%|                                                                           | 0/3 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 33%|██████████████████████▎                                            | 1/3 [00:22<00:44, 22.27s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 67%|████████████████████████████████████████████▋                      | 2/3 [00:39<00:19, 19.32s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|███████████████████████████████████████████████████████████████████| 3/3 [00:52<00:00, 17.53s/it]

disgust

  0%|                                                                           | 0/2 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|█████████████████████████████████▌                                 | 1/2 [00:18<00:18, 18.97s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|███████████████████████████████████████████████████████████████████| 2/2 [00:34<00:00, 17.13s/it]

fear

  0%|                                                                          | 0/20 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
  5%|███▎                                                              | 1/20 [00:18<05:56, 18.77s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 2/20 [00:36<05:31, 18.40s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 15%|█████████▉                                                        | 3/20 [00:55<05:11, 18.32s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 4/20 [01:12<04:44, 17.80s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 25%|████████████████▌                                                 | 5/20 [01:29<04:23, 17.56s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 6/20 [01:47<04:11, 17.95s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 35%|███████████████████████                                           | 7/20 [02:07<04:01, 18.58s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 8/20 [02:26<03:44, 18.70s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 45%|█████████████████████████████▋                                    | 9/20 [02:45<03:24, 18.63s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|████████████████████████████████▌                                | 10/20 [03:03<03:05, 18.52s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 55%|███████████████████████████████████▊                             | 11/20 [03:22<02:48, 18.72s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████                          | 12/20 [03:41<02:30, 18.77s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 65%|██████████████████████████████████████████▎                      | 13/20 [03:59<02:09, 18.46s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|█████████████████████████████████████████████▌                   | 14/20 [04:17<01:51, 18.51s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 75%|████████████████████████████████████████████████▊                | 15/20 [04:34<01:29, 17.97s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████             | 16/20 [04:51<01:10, 17.56s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 85%|███████████████████████████████████████████████████████▎         | 17/20 [05:07<00:51, 17.27s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|██████████████████████████████████████████████████████████▌      | 18/20 [05:25<00:34, 17.48s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 95%|█████████████████████████████████████████████████████████████▊   | 19/20 [05:45<00:17, 17.98s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 20/20 [06:03<00:00, 18.19s/it]

happy

  0%|                                                                          | 0/20 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
  5%|███▎                                                              | 1/20 [00:16<05:21, 16.91s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 2/20 [00:35<05:24, 18.02s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 15%|█████████▉                                                        | 3/20 [00:53<05:08, 18.12s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 4/20 [01:11<04:45, 17.82s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 25%|████████████████▌                                                 | 5/20 [01:29<04:27, 17.81s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 6/20 [01:46<04:06, 17.61s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 35%|███████████████████████                                           | 7/20 [02:05<03:53, 17.96s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 8/20 [02:22<03:33, 17.76s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 45%|█████████████████████████████▋                                    | 9/20 [02:38<03:11, 17.38s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|████████████████████████████████▌                                | 10/20 [02:56<02:54, 17.42s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 55%|███████████████████████████████████▊                             | 11/20 [03:14<02:39, 17.69s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████                          | 12/20 [03:32<02:21, 17.71s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 65%|██████████████████████████████████████████▎                      | 13/20 [03:51<02:06, 18.06s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|█████████████████████████████████████████████▌                   | 14/20 [04:09<01:49, 18.22s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 75%|████████████████████████████████████████████████▊                | 15/20 [04:27<01:29, 17.98s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████             | 16/20 [04:46<01:12, 18.25s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|██████████████████████████████████████████████████████████▌      | 18/20 [05:22<00:36, 18.32s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 95%|█████████████████████████████████████████████████████████████▊   | 19/20 [05:42<00:18, 18.70s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 20/20 [06:01<00:00, 18.08s/it]

neutral

  0%|                                                                          | 0/20 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
  5%|███▎                                                              | 1/20 [00:19<06:04, 19.18s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 2/20 [00:36<05:28, 18.25s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 15%|█████████▉                                                        | 3/20 [00:54<05:06, 18.05s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 4/20 [01:13<04:53, 18.34s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 25%|████████████████▌                                                 | 5/20 [01:32<04:36, 18.46s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 6/20 [01:50<04:17, 18.40s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 35%|███████████████████████                                           | 7/20 [02:09<04:01, 18.55s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 8/20 [02:27<03:43, 18.62s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 45%|█████████████████████████████▋                                    | 9/20 [02:46<03:25, 18.70s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|████████████████████████████████                                | 10/20 [21:19<59:23, 356.32s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 55%|███████████████████████████████████▏                            | 11/20 [21:38<37:57, 253.07s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|██████████████████████████████████████▍                         | 12/20 [21:55<24:12, 181.51s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 65%|█████████████████████████████████████████▌                      | 13/20 [22:14<15:24, 132.13s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|█████████████████████████████████████████████▌                   | 14/20 [22:31<09:44, 97.49s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 75%|████████████████████████████████████████████████▊                | 15/20 [22:50<06:08, 73.60s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████             | 16/20 [23:07<03:46, 56.66s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 85%|███████████████████████████████████████████████████████▎         | 17/20 [23:26<02:16, 45.35s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|██████████████████████████████████████████████████████████▌      | 18/20 [23:45<01:14, 37.48s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 95%|█████████████████████████████████████████████████████████████▊   | 19/20 [24:03<00:31, 31.68s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 20/20 [24:21<00:00, 73.07s/it]

sad

  0%|                                                                          | 0/20 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
  5%|███▎                                                              | 1/20 [00:18<05:42, 18.02s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 2/20 [00:34<05:10, 17.24s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 15%|█████████▉                                                        | 3/20 [00:51<04:50, 17.06s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 4/20 [01:07<04:27, 16.72s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 25%|████████████████▌                                                 | 5/20 [01:26<04:19, 17.32s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 6/20 [01:43<04:02, 17.29s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 35%|███████████████████████                                           | 7/20 [02:01<03:46, 17.40s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 8/20 [02:19<03:31, 17.64s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 45%|█████████████████████████████▋                                    | 9/20 [02:35<03:11, 17.38s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|████████████████████████████████▌                                | 10/20 [02:53<02:52, 17.28s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 55%|███████████████████████████████████▊                             | 11/20 [03:11<02:37, 17.50s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████                          | 12/20 [03:30<02:25, 18.14s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 65%|██████████████████████████████████████████▎                      | 13/20 [03:48<02:06, 18.04s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|█████████████████████████████████████████████▌                   | 14/20 [04:06<01:48, 18.14s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 75%|████████████████████████████████████████████████▊                | 15/20 [04:25<01:32, 18.44s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████             | 16/20 [04:44<01:14, 18.56s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 85%|███████████████████████████████████████████████████████▎         | 17/20 [05:04<00:56, 18.83s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|██████████████████████████████████████████████████████████▌      | 18/20 [05:22<00:37, 18.69s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 95%|█████████████████████████████████████████████████████████████▊   | 19/20 [05:40<00:18, 18.54s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 20/20 [05:59<00:00, 17.98s/it]

surprise

  0%|                                                                          | 0/20 [00:00<?, ?it/s]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
  5%|███▎                                                              | 1/20 [00:19<06:02, 19.09s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 10%|██████▌                                                           | 2/20 [00:37<05:39, 18.87s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 15%|█████████▉                                                        | 3/20 [00:56<05:16, 18.62s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 20%|█████████████▏                                                    | 4/20 [01:14<04:53, 18.34s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 25%|████████████████▌                                                 | 5/20 [01:33<04:40, 18.73s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 30%|███████████████████▊                                              | 6/20 [01:52<04:22, 18.78s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 35%|███████████████████████                                           | 7/20 [02:09<03:59, 18.39s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 40%|██████████████████████████▍                                       | 8/20 [02:28<03:40, 18.40s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 45%|█████████████████████████████▋                                    | 9/20 [02:46<03:22, 18.39s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 50%|████████████████████████████████▌                                | 10/20 [03:04<03:01, 18.18s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 55%|███████████████████████████████████▊                             | 11/20 [03:23<02:47, 18.56s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 60%|███████████████████████████████████████                          | 12/20 [03:42<02:29, 18.65s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 65%|██████████████████████████████████████████▎                      | 13/20 [04:02<02:12, 18.99s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 70%|█████████████████████████████████████████████▌                   | 14/20 [04:20<01:51, 18.56s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 75%|████████████████████████████████████████████████▊                | 15/20 [04:37<01:31, 18.30s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 80%|████████████████████████████████████████████████████             | 16/20 [04:55<01:12, 18.12s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 85%|███████████████████████████████████████████████████████▎         | 17/20 [05:13<00:54, 18.01s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 90%|██████████████████████████████████████████████████████████▌      | 18/20 [05:29<00:35, 17.55s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
 95%|█████████████████████████████████████████████████████████████▊   | 19/20 [05:47<00:17, 17.59s/it]C:\Users\adria\OneDrive\Documentos\Programs\IIS\IIS\Lib\site-packages\feat\detector.py:1021: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(out)
100%|█████████████████████████████████████████████████████████████████| 20/20 [06:05<00:00, 18.26s/it]

In [5]:
df

,emotion,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,input,frame
0,angry,4.415638,-2.330682,37.994838,45.224039,0.829163,4.455236,6.218436,8.532767,11.774168,...,0.433263,0.976708,0.003710,0.001177,0.007107,0.001021,0.008138,0.002139,./train/angry/612.jpg,0
1,angry,7.400880,0.041491,36.878879,47.122725,0.957859,13.044603,13.045285,13.866569,15.450356,...,0.044235,0.133992,0.000312,0.000975,0.017545,0.007338,0.089984,0.749854,./train/angry/617.jpg,1
2,angry,0.636619,2.318507,44.887024,43.750138,0.895846,7.656421,9.148557,11.196274,13.953809,...,0.139236,0.859599,0.013137,0.002201,0.015102,0.024665,0.009527,0.075769,./train/angry/625.jpg,2
3,angry,8.377713,3.391628,37.126323,43.501019,0.992113,8.107041,9.454854,11.163122,13.394255,...,0.730263,0.913633,0.079068,0.000344,0.001168,0.000574,0.002153,0.003059,./train/angry/636.jpg,3
4,angry,1.058513,-4.148475,47.148705,59.180079,0.594674,7.703610,7.102890,7.630177,9.836632,...,0.245539,0.979968,0.000720,0.002304,0.009708,0.000324,0.006888,0.000088,./train/angry/671.jpg,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,surprise,7.492670,3.988891,34.174009,44.487542,0.868986,11.976515,11.766769,12.174930,13.427995,...,0.081488,0.047993,0.000198,0.073429,0.002209,0.000258,0.875670,0.000244,./train/surprise/1859.jpg,395
396,surprise,4.733178,8.069610,33.212673,37.080316,0.995263,1.434274,2.272086,3.304874,4.716947,...,0.043697,0.002813,0.002507,0.001993,0.001006,0.005043,0.779413,0.207226,./train/surprise/18590.jpg,396
397,surprise,2.789320,-1.120940,39.624949,50.881064,0.993781,4.781996,5.559071,7.239025,9.738993,...,0.058477,0.002286,0.000021,0.000353,0.000011,0.000018,0.995937,0.001373,./train/surprise/18595.jpg,397
398,surprise,2.314616,-0.996317,40.973603,51.374834,0.977426,6.484198,6.908202,8.145332,9.929646,...,0.137738,0.011864,0.000593,0.031277,0.032289,0.013240,0.885867,0.024870,./train/surprise/18605.jpg,398
399,surprise,4.305536,-0.171212,38.889124,48.502736,0.977940,7.610516,7.457456,7.963562,9.213744,...,0.255163,0.000311,0.000029,0.021504,0.000901,0.000308,0.970786,0.006160,./train/surprise/18618.jpg,399

In [6]:
original = df.copy()
df=df.dropna(axis=0)
df

,emotion,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,input,frame
1,angry,7.400880,0.041491,36.878879,47.122725,0.957859,13.044603,13.045285,13.866569,15.450356,...,0.044235,0.133992,0.000312,0.000975,0.017545,0.007338,0.089984,0.749854,./train/angry/617.jpg,1
3,angry,8.377713,3.391628,37.126323,43.501019,0.992113,8.107041,9.454854,11.163122,13.394255,...,0.730263,0.913633,0.079068,0.000344,0.001168,0.000574,0.002153,0.003059,./train/angry/636.jpg,3
5,angry,3.498964,0.075425,40.681445,48.548633,0.932897,2.418505,3.232710,4.732525,6.713168,...,0.036191,0.999297,0.000028,0.000009,0.000002,0.000258,0.000028,0.000379,./train/angry/677.jpg,5
7,angry,3.478887,4.330705,36.245452,44.191489,0.804013,8.761497,9.979857,11.926531,14.643355,...,0.278808,0.990438,0.002750,0.000018,0.000143,0.000027,0.003779,0.002845,./train/angry/700.jpg,7
9,angry,2.666662,-1.251801,29.406977,44.804409,0.987351,5.041080,4.076685,3.858066,4.689112,...,0.049859,0.600942,0.138119,0.024297,0.014468,0.095996,0.110554,0.015624,./train/angry/714.jpg,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,surprise,7.492670,3.988891,34.174009,44.487542,0.868986,11.976515,11.766769,12.174930,13.427995,...,0.081488,0.047993,0.000198,0.073429,0.002209,0.000258,0.875670,0.000244,./train/surprise/1859.jpg,395
396,surprise,4.733178,8.069610,33.212673,37.080316,0.995263,1.434274,2.272086,3.304874,4.716947,...,0.043697,0.002813,0.002507,0.001993,0.001006,0.005043,0.779413,0.207226,./train/surprise/18590.jpg,396
397,surprise,2.789320,-1.120940,39.624949,50.881064,0.993781,4.781996,5.559071,7.239025,9.738993,...,0.058477,0.002286,0.000021,0.000353,0.000011,0.000018,0.995937,0.001373,./train/surprise/18595.jpg,397
398,surprise,2.314616,-0.996317,40.973603,51.374834,0.977426,6.484198,6.908202,8.145332,9.929646,...,0.137738,0.011864,0.000593,0.031277,0.032289,0.013240,0.885867,0.024870,./train/surprise/18605.jpg,398
399,surprise,4.305536,-0.171212,38.889124,48.502736,0.977940,7.610516,7.457456,7.963562,9.213744,...,0.255163,0.000311,0.000029,0.021504,0.000901,0.000308,0.970786,0.006160,./train/surprise/18618.jpg,399

In [7]:
cpy = df.copy()
AUcol = [col for col in cpy if col.startswith('AU')]
cpy = cpy[["emotion"] + AUcol]
data = pd.read_csv(filepath_or_buffer = "aus000400.csv")
data = pd.concat([data, cpy])
data.to_csv('aus000800.csv', index=False)  
data

,emotion,AU01,AU02,AU04,AU05,AU06,AU07,AU09,AU10,AU11,...,AU14,AU15,AU17,AU20,AU23,AU24,AU25,AU26,AU28,AU43
0,neutral,0.450774,0.289915,0.409713,0.518726,0.086218,0.0,0.187309,0.354838,0.0,...,0.320690,0.411641,0.431646,0.0,0.277122,0.335435,0.262999,0.189863,0.051967,0.051370
1,disgust,0.500450,0.314694,0.625174,0.335747,0.262984,0.0,0.504238,0.383201,0.0,...,0.544159,0.440429,0.495913,0.0,0.514737,0.420401,0.052358,0.143576,0.500994,0.155117
2,sad,0.273191,0.191327,0.140938,0.358091,0.246593,0.0,0.312881,0.188845,1.0,...,0.284598,0.761539,0.491468,0.0,0.134049,0.670237,0.024796,0.109462,0.325429,0.191367
3,neutral,0.464508,0.301702,0.500370,0.296161,0.189114,0.0,0.521304,0.039475,0.0,...,0.491734,0.163430,0.552469,0.0,0.419418,0.306920,0.224105,0.072518,0.652248,0.505568
4,happy,0.274483,0.232007,0.601821,0.281365,0.900241,1.0,0.784789,0.198816,0.0,...,0.703261,0.549239,0.425561,0.0,0.203916,0.561599,0.966706,0.108249,0.464104,0.786888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,surprise,0.286238,0.280478,0.265697,0.389420,0.135243,0.0,0.177137,0.034033,1.0,...,0.234049,0.044919,0.377693,0.0,0.479738,0.473496,0.001186,0.038493,0.554120,0.081488
396,surprise,0.454190,0.363297,0.384982,0.655245,0.067271,0.0,0.141455,0.003330,1.0,...,0.398199,0.372062,0.381510,0.0,0.632767,0.455080,0.532713,0.334236,0.328923,0.043697
397,surprise,0.537069,0.423002,0.506382,0.739671,0.043524,0.0,0.127783,0.160912,1.0,...,0.172529,0.211914,0.302350,0.0,0.604603,0.082204,0.951915,0.356218,0.609324,0.058477
398,surprise,0.680042,0.609784,0.438708,0.553386,0.107358,0.0,0.133100,0.524864,0.0,...,0.445182,0.576752,0.587063,1.0,0.673313,0.087795,0.925344,0.382966,0.362068,0.137738
399,surprise,0.279840,0.158416,0.349169,0.308240,0.290075,1.0,0.483181,0.000160,1.0,...,0.299985,0.208105,0.523637,0.0,0.537634,0.411017,0.416471,0.332083,0.207702,0.255163